import type { KnowledgePassage } from "../types";

/**
 * Pasajes documentales (parafraseados, no citas textuales). Sólo contenido anterior a 1951-05-01.
 * `confidence: "media"` = dato razonablemente establecido pero con fecha/detalle a cotejar.
 * Una ficha sólo aparece en la interfaz como DOCUMENTADO si fue recuperada en ese turno.
 */
export const PERON_KNOWLEDGE: KnowledgePassage[] = [
  {
    id: "K-bio-origen",
    source_ids: ["S-BIO-PAGE", "S-BIO-LUNA"],
    topics: ["biografía", "infancia", "carrera militar"],
    keywords: ["nació", "nacimiento", "Lobos", "Colegio Militar", "subteniente", "infantería", "Escuela Superior de Guerra", "infancia", "familia"],
    as_of: "1913-12-31",
    text: "Perón nació el 8 de octubre de 1895; el acta lo ubica en Lobos, provincia de Buenos Aires (se discutió si fue en Roque Pérez). Ingresó al Colegio Militar en 1911 y egresó como subteniente de infantería en 1913. Más tarde fue profesor en la Escuela Superior de Guerra.",
    confidence: "alta",
  },
  {
    id: "K-bio-exterior",
    source_ids: ["S-BIO-PAGE", "S-POTASH"],
    topics: ["biografía", "Italia", "Chile", "guerra"],
    keywords: ["Italia", "Chile", "agregado militar", "Alpini", "montaña", "Mussolini", "fascismo", "Europa", "guerra"],
    as_of: "1941-12-31",
    text: "Fue agregado militar en Chile (1936-1938) y estuvo en Italia entre 1939 y 1941, donde se formó con tropas de montaña y vio de cerca la Europa en guerra y el fascismo.",
    confidence: "media",
  },
  {
    id: "K-bio-viudez",
    source_ids: ["S-BIO-PAGE"],
    topics: ["biografía", "familia"],
    keywords: ["Aurelia", "Tizón", "Potota", "primera esposa", "viudo", "viudez", "casó"],
    as_of: "1938-09-10",
    text: "Su primera esposa, Aurelia Tizón, murió el 10 de septiembre de 1938. Perón quedó viudo y siguió su carrera militar antes de conocer a Eva.",
    confidence: "alta",
  },
  {
    id: "K-1943-trabajo",
    source_ids: ["S-POTASH", "S-BIO-LUNA"],
    topics: ["1943", "GOU", "sindicatos", "legislación social"],
    keywords: ["GOU", "1943", "golpe", "Secretaría de Trabajo", "Trabajo y Previsión", "sindicatos", "obreros", "convenios", "aguinaldo", "vacaciones", "estatuto del peón"],
    as_of: "1945-12-31",
    text: "Perón integró el grupo de oficiales GOU y participó del golpe del 4 de junio de 1943. Desde la Secretaría de Trabajo y Previsión (fines de 1943) construyó su vínculo con los sindicatos y promovió legislación social; entre las medidas de esa etapa se cuentan el estatuto del peón, las vacaciones pagas y el aguinaldo.",
    confidence: "media",
  },
  {
    id: "K-1945-17oct",
    source_ids: ["S-BIO-LUNA", "S-BIO-PAGE"],
    topics: ["1945", "17 de octubre", "origen del movimiento"],
    keywords: ["17 de octubre", "1945", "Martín García", "detención", "Plaza de Mayo", "lealtad", "renuncia", "descamisados"],
    as_of: "1945-10-17",
    text: "En octubre de 1945, presionado por sectores militares y opositores, Perón fue obligado a renunciar y detenido, trasladado a la isla Martín García. El 17 de octubre una movilización obrera masiva en Plaza de Mayo exigió su libertad; ese día se considera el origen político del movimiento peronista.",
    confidence: "alta",
  },
  {
    id: "K-1946-presidencia",
    source_ids: ["S-BIO-LUNA"],
    topics: ["elecciones", "presidencia"],
    keywords: ["elecciones", "1946", "presidencia", "asumió", "24 de febrero", "4 de junio", "ganó"],
    as_of: "1946-06-04",
    text: "Perón ganó las elecciones del 24 de febrero de 1946 y asumió la presidencia el 4 de junio de 1946.",
    confidence: "alta",
  },
  {
    id: "K-eva-vida",
    source_ids: ["S-BIO-NAVARRO", "S-BIO-LUNA"],
    topics: ["Eva Perón", "matrimonio"],
    keywords: ["Eva", "Evita", "esposa", "casamiento", "Junín", "La Plata", "Luna Park", "San Juan", "terremoto", "cumpleaños", "radio", "actriz"],
    as_of: "1945-12-10",
    text: "Eva Duarte fue actriz y locutora de radio. Perón y Eva se conocieron el 22 de enero de 1944 en un festival a beneficio de las víctimas del terremoto de San Juan. Se casaron por civil el 22 de octubre de 1945 en Junín y por la Iglesia en La Plata, en diciembre de 1945. Su cumpleaños es el 7 de mayo.",
    confidence: "media",
  },
  {
    id: "K-eva-politica",
    source_ids: ["S-BIO-NAVARRO", "S-LEY13010"],
    topics: ["Eva Perón", "Fundación", "voto femenino", "Partido Peronista Femenino"],
    keywords: ["Eva", "Evita", "Fundación", "ayuda social", "voto femenino", "mujeres", "Partido Peronista Femenino", "descamisados", "sindicatos", "obreros", "ley 13010"],
    as_of: "1950-12-31",
    text: "Eva tiene un vínculo directo y propio con los trabajadores y los sindicatos. Encabeza la Fundación de Ayuda Social María Eva Duarte de Perón (creada en 1948, luego llamada Fundación Eva Perón) y preside el Partido Peronista Femenino, fundado el 26 de julio de 1949. La ley 13.010 (septiembre de 1947) estableció los derechos políticos de la mujer: la primera elección nacional con voto femenino todavía no se hizo.",
    confidence: "media",
  },
  {
    id: "K-plan-quinquenal",
    source_ids: ["S-PLAN1", "S-INDEP"],
    topics: ["economía", "industria", "nacionalizaciones", "independencia económica"],
    keywords: ["Plan Quinquenal", "industrialización", "industria", "nacionalización", "ferrocarriles", "Banco Central", "independencia económica", "Tucumán", "9 de julio", "obra pública", "energía", "vivienda"],
    as_of: "1948-03-01",
    text: "El Primer Plan Quinquenal (1947-1951) fijó metas de industrialización, obra pública, energía, salud y vivienda. Entre las nacionalizaciones están el Banco Central (1946) y los ferrocarriles británicos, traspasados al Estado el 1 de marzo de 1948. El 9 de julio de 1947, en Tucumán, se proclamó la independencia económica.",
    confidence: "alta",
  },
  {
    id: "K-constitucion-1949",
    source_ids: ["S-CONST49"],
    topics: ["constitución", "derechos del trabajador", "reelección"],
    keywords: ["Constitución", "reforma", "1949", "reelección", "derechos del trabajador", "función social", "propiedad", "recursos naturales", "constituyente"],
    as_of: "1949-03-16",
    text: "La reforma constitucional de 1949 incorporó derechos del trabajador, la función social de la propiedad y normas sobre recursos naturales y servicios públicos, y habilitó la reelección presidencial inmediata.",
    confidence: "alta",
  },
  {
    id: "K-comunidad-organizada",
    source_ids: ["S-COMUNIDAD"],
    topics: ["doctrina", "comunidad organizada", "tercera posición"],
    keywords: ["Comunidad Organizada", "Mendoza", "Congreso de Filosofía", "individuo", "comunidad", "filosofía", "tercera posición", "individualismo", "colectivismo"],
    as_of: "1949-04-09",
    text: "El 9 de abril de 1949, al cierre del Congreso Nacional de Filosofía en Mendoza, Perón expuso La Comunidad Organizada: una concepción que busca equilibrar al individuo y a la comunidad, y superar tanto el individualismo liberal como el colectivismo, en línea con la llamada tercera posición.",
    confidence: "media",
  },
  {
    id: "K-veinte-verdades",
    source_ids: ["S-20VERDADES"],
    topics: ["doctrina", "justicia social", "lealtad"],
    keywords: ["Veinte Verdades", "verdades", "doctrina", "justicia social", "independencia económica", "soberanía política", "lealtad", "justicialismo", "17 de octubre de 1950"],
    as_of: "1950-10-17",
    text: "El 17 de octubre de 1950 se proclamaron las Veinte Verdades del Justicialista, un resumen doctrinario cuyas banderas son la justicia social, la independencia económica y la soberanía política, con el trabajo, la lealtad y la unidad del pueblo como ejes.",
    confidence: "alta",
  },
  {
    id: "K-conduccion",
    source_ids: ["S-CONDPOL", "S-DOSSIER"],
    topics: ["conducción", "estrategia", "táctica", "organización"],
    keywords: ["conducción", "estrategia", "táctica", "organización", "método", "apreciación de situación", "mando", "Escuela Superior Peronista", "conducir"],
    as_of: "1951-04-30",
    text: "Perón concibe la conducción política como un arte con método, que toma del arte militar las nociones de estrategia, táctica y apreciación de situación, y que depende de la organización y preparación del pueblo; distingue conducir de mandar. En 1951 desarrolla estas ideas en clases en la Escuela Superior Peronista.",
    confidence: "media",
  },
  {
    id: "K-sindicatos",
    source_ids: ["S-BIO-LUNA", "S-BIO-PAGE"],
    topics: ["sindicatos", "CGT", "movimiento obrero"],
    keywords: ["CGT", "sindicatos", "gremios", "trabajadores", "obreros", "Espejo", "personería gremial", "movimiento obrero", "1 de mayo", "Día del Trabajo"],
    as_of: "1951-04-30",
    text: "La CGT es el pilar organizado del movimiento; su secretario general desde 1947 es José Espejo. El esquema gremial se apoya en la personería gremial por rama. El 1 de mayo, Día del Trabajo, es una fecha central del movimiento obrero.",
    confidence: "media",
  },
  {
    id: "K-salud",
    source_ids: ["S-BIO-LUNA"],
    topics: ["salud pública", "Carrillo"],
    keywords: ["Carrillo", "Ramón Carrillo", "salud pública", "hospitales", "paludismo", "tuberculosis", "médicos", "medicina", "sanitaria"],
    as_of: "1950-12-31",
    text: "Ramón Carrillo conduce la política sanitaria (Secretaría de Salud Pública desde 1946 y Ministerio desde 1949), con un plan de construcción de hospitales y campañas contra el paludismo y la tuberculosis.",
    confidence: "media",
  },
  {
    id: "K-internacional-1951",
    source_ids: ["S-BIO-PAGE"],
    topics: ["política internacional", "Guerra Fría", "Corea", "tercera posición"],
    keywords: ["Guerra Fría", "Corea", "tercera guerra mundial", "Estados Unidos", "Unión Soviética", "tercera posición", "neutralidad", "comunismo", "capitalismo", "internacional"],
    as_of: "1951-04-30",
    text: "La Guerra Fría y la guerra de Corea (desde junio de 1950) hacen temer una tercera guerra mundial. La tercera posición busca no alinearse automáticamente con Estados Unidos ni con la Unión Soviética, manteniendo comercio con ambos bloques.",
    confidence: "media",
  },
  {
    id: "K-economia-1951",
    source_ids: ["S-PLAN1", "S-BIO-LUNA"],
    topics: ["economía", "balanza de pagos", "sequía"],
    keywords: ["sequía", "balanza de pagos", "divisas", "inflación", "economía", "cosecha", "exportaciones", "crisis", "precios"],
    as_of: "1951-04-30",
    text: "Desde 1949 las sequías y los problemas de balanza de pagos obligan a cuidar las divisas, y se discute cómo sostener la industrialización y los salarios sin desbordar los precios. Las cifras exactas conviene consultarlas con los ministros.",
    confidence: "media",
  },
  {
    id: "K-la-prensa-1951",
    source_ids: ["S-BIO-LUNA"],
    topics: ["prensa", "libertad de prensa", "oposición"],
    keywords: ["La Prensa", "diario", "prensa", "libertad de prensa", "expropiación", "Gainza Paz", "oposición", "periodismo", "clausura", "conflicto gremial"],
    as_of: "1951-04-30",
    text: "La Prensa, diario opositor de la familia Gainza Paz, dejó de aparecer en enero de 1951 tras un conflicto gremial, y el Congreso avanzó con su expropiación (fecha exacta a verificar). La oposición lo denuncia como un ataque a la libertad de prensa; el oficialismo lo presenta como un conflicto laboral y de intereses.",
    confidence: "media",
  },
  {
    id: "K-reeleccion-1951",
    source_ids: ["S-CONST49"],
    topics: ["reelección", "elecciones 1951"],
    keywords: ["reelección", "candidatura", "elecciones", "1951", "noviembre", "presidente", "reelegir", "fórmula"],
    as_of: "1951-04-30",
    text: "La reforma de 1949 permite la reelección inmediata y se preparan las elecciones presidenciales, previstas para fines de 1951. Su resultado no es conocido.",
    confidence: "media",
  },
];
