import type { SourceRecord } from "../types";

/**
 * Registro de fuentes. `url_checked: false` significa que la ficha existe pero nadie abrió aún el original
 * para confirmar URL/edición/páginas: la interfaz lo muestra como "ficha pendiente de verificación".
 * No se agregan fuentes que no se hayan podido identificar con certeza.
 */
export const PERON_SOURCES: SourceRecord[] = [
  {
    source_id: "S-DOSSIER",
    title: "Dossier maestro de Perón (/ACTIVAR_PERON)",
    author: "Proyecto Historia Viva (especificación del personaje)",
    date: "2026-10-08",
    type: "especificación interna",
    url_archive: "characters/peron/source/dossier-activar-peron.txt",
    historical_period: "1951",
    reliability: "C",
    topics: ["personalidad", "modelo de decisión", "reglas de conversación"],
    notes: "Define la mente y reglas del personaje. No es fuente histórica primaria.",
    url_checked: true,
  },
  {
    source_id: "S-ANEXO-A",
    title: "Anexo A — Motor de conversación humana y realista",
    author: "Proyecto Historia Viva (especificación del personaje)",
    date: "2026-10-08",
    type: "especificación interna",
    url_archive: "characters/peron/source/anexo-a-conversacion.txt",
    historical_period: "1951",
    reliability: "C",
    topics: ["estilo conversacional", "memoria", "confianza progresiva"],
    notes: "Reglas de ritmo, interrupción, memoria y confianza.",
    url_checked: true,
  },
  {
    source_id: "S-COMUNIDAD",
    title: "La Comunidad Organizada (exposición en el Congreso Nacional de Filosofía)",
    author: "Juan Domingo Perón",
    date: "1949-04-09",
    type: "discurso / texto doctrinal",
    url_archive: "Mendoza, Universidad Nacional de Cuyo, 1949 (ubicar edición de las actas del Congreso)",
    historical_period: "1949",
    reliability: "B",
    topics: ["doctrina", "comunidad organizada", "tercera posición"],
    notes: "Texto del propio Perón. Falta cotejar edición y paginación.",
    url_checked: false,
  },
  {
    source_id: "S-CONDPOL",
    title: "Conducción Política",
    author: "Juan Domingo Perón",
    date: "1951",
    type: "clases / libro doctrinal",
    url_archive: "Escuela Superior Peronista, 1951 (publicación posterior; ubicar edición)",
    historical_period: "1951-1952",
    reliability: "B",
    topics: ["conducción", "organización", "estrategia y táctica"],
    notes: "Base del modelo mental. Verificar fechas de dictado y edición antes de citar páginas.",
    url_checked: false,
  },
  {
    source_id: "S-20VERDADES",
    title: "Las Veinte Verdades Peronistas (Justicialistas)",
    author: "Juan Domingo Perón",
    date: "1950-10-17",
    type: "documento doctrinal",
    url_archive: "Proclamadas el 17 de octubre de 1950 (ubicar texto oficial)",
    historical_period: "1950",
    reliability: "B",
    topics: ["doctrina", "lealtad", "trabajo"],
    notes: "Resumen doctrinario. Cotejar texto oficial.",
    url_checked: false,
  },
  {
    source_id: "S-PLAN1",
    title: "Plan de Gobierno 1947-1951 (Primer Plan Quinquenal)",
    author: "Presidencia de la Nación",
    date: "1946-10-21",
    type: "documento oficial",
    url_archive: "Archivo General de la Nación / Biblioteca del Congreso (ubicar edición)",
    historical_period: "1947-1951",
    reliability: "A",
    topics: ["economía", "industrialización", "nacionalizaciones", "plan quinquenal"],
    notes: "Documento oficial de planificación. Verificar fecha de presentación al Congreso.",
    url_checked: false,
  },
  {
    source_id: "S-CONST49",
    title: "Constitución de la Nación Argentina (reforma de 1949)",
    author: "Convención Nacional Constituyente",
    date: "1949-03-11",
    type: "documento oficial",
    url_archive: "Boletín Oficial / Biblioteca del Congreso (ubicar texto)",
    historical_period: "1949",
    reliability: "A",
    topics: ["constitución", "derechos del trabajador", "reelección"],
    notes: "Texto constitucional; verificar numeración de artículos antes de citar.",
    url_checked: false,
  },
  {
    source_id: "S-LEY13010",
    title: "Ley 13.010 — Derechos políticos de la mujer",
    author: "Congreso de la Nación",
    date: "1947-09-23",
    type: "documento oficial",
    url_archive: "Boletín Oficial / InfoLEG (ubicar)",
    historical_period: "1947",
    reliability: "A",
    topics: ["voto femenino", "derechos políticos"],
    notes: "Verificar fecha de sanción y promulgación.",
    url_checked: false,
  },
  {
    source_id: "S-INDEP",
    title: "Declaración de la independencia económica (Tucumán, 9 de julio de 1947)",
    author: "Juan Domingo Perón",
    date: "1947-07-09",
    type: "discurso / acta",
    url_archive: "Casa Histórica de Tucumán / Presidencia (ubicar texto)",
    historical_period: "1947",
    reliability: "B",
    topics: ["independencia económica", "soberanía"],
    notes: "Cotejar texto de la acta y del discurso.",
    url_checked: false,
  },
  {
    source_id: "S-BIO-PAGE",
    title: "Perón: A Biography",
    author: "Joseph A. Page",
    date: "1983",
    type: "biografía académica",
    url_archive: "Random House, 1983",
    historical_period: "1895-1974",
    reliability: "C",
    topics: ["biografía", "carrera militar", "ascenso político"],
    notes: "Biografía extensa. Cotejar cada dato con fuentes primarias.",
    url_checked: false,
  },
  {
    source_id: "S-BIO-LUNA",
    title: "Perón y su tiempo",
    author: "Félix Luna",
    date: "1984",
    type: "historiografía",
    url_archive: "Sudamericana, 1984-1986 (3 vols.)",
    historical_period: "1943-1955",
    reliability: "C",
    topics: ["política", "1945", "primer gobierno"],
    notes: "Obra de referencia; cotejar fechas y cifras.",
    url_checked: false,
  },
  {
    source_id: "S-POTASH",
    title: "The Army and Politics in Argentina, 1928-1945: Yrigoyen to Perón",
    author: "Robert A. Potash",
    date: "1969",
    type: "historiografía académica",
    url_archive: "Stanford University Press, 1969",
    historical_period: "1928-1945",
    reliability: "C",
    topics: ["ejército", "GOU", "1943"],
    notes: "Estudio documentado del ejército y el golpe de 1943.",
    url_checked: false,
  },
  {
    source_id: "S-BIO-NAVARRO",
    title: "Evita",
    author: "Marysa Navarro",
    date: "1994",
    type: "biografía académica",
    url_archive: "Edición en español de Planeta (ubicar edición exacta)",
    historical_period: "1919-1952",
    reliability: "C",
    topics: ["Eva Perón", "Fundación", "Partido Peronista Femenino"],
    notes: "Biografía académica de Eva. Verificar edición antes de citar.",
    url_checked: false,
  },
];
